##
##  Makefile -- Build procedure for sample acl Apache module
##  Autogenerated via ``apxs -n acl -g''.
##

ifndef HRP_VERSION
$(error HRP_VERSION is not set, must be "HRP_VERSION=SSL5" or "HRP_VERSION=SSL6")
endif

builddir=$(shell pwd)
ifeq ($(HRP_VERSION),SSL5)
top_srcdir=/kssl/HRP/.prefork
HRP_BIN=/kssl/HRP/bin/HRPd.prefork
else
top_srcdir=/kssl/HRP
HRP_BIN=/kssl/HRP/bin/HRPd
endif

top_builddir=$(top_srcdir)
include $(top_builddir)/build/special.mk

APXS=apxs
APACHECTL=$(top_builddir)/bin/apachectl

GDB=gdb

CXX=g++
# NOTEST_CPPFLAS set empty here to clear -DAP_HAVE_DESIGNATED_INITIALIZER
NOTEST_CPPFLAGS=
CXXFLAGS=-Wall -I$(builddir)/.. -I./third_party/SQLiteCpp/include -I./third_party/SQLiteCpp/sqlite3 -I./third_party/boost  # g++3.3 does NOT support -fvisibility=hidden -Wextra

#   the default target
all: local-shared-build

#   install the shared object file into Apache
#install: install-modules-yes
install:
	cp .libs/mod_passauth.so ${top_builddir}/lib/

#   cleanup
clean:
	-rm -f acl_localdb_test

#   simple test
test:
	curl -k https://127.0.0.1:9876


unittest: acl_localdb_test
	./$<


start:
	$(HRP_BIN) -d $(builddir)/tests -D$(HRP_VERSION) -k start -e debug -f httpd.conf
restart:
	$(HRP_BIN) -d $(builddir)/tests -D$(HRP_VERSION) -k restart -e debug -f httpd.conf
stop:
	$(HRP_BIN) -d $(builddir)/tests -D$(HRP_VERSION) -k stop -e debug -f httpd.conf

gdb:
	$(GDB) --args $(HRP_BIN) -d $(builddir)/tests -D$(HRP_VERSION) -k start -e debug -DDEBUG -X -f httpd.conf
